%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ESpurbeck.P3E-HIGHBAY-01\Desktop\LANL Project\GUI\Python Testing\rigol1_20251208_110512.csv
%
% Auto-generated by MATLAB on 08-Dec-2025 11:06:22

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time_s", "ch1_v", "ch2_v"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("C:\Users\ESpurbeck.P3E-HIGHBAY-01\Desktop\LANL Project\GUI\Python Testing\rigol1_20251208_110512.csv", opts);


%% Clear temporary variables
clear opts


t   = data.time_s;   % time in seconds
v1  = data.ch1_v;    % channel 1
v2  = data.ch2_v;    % channel 2

%=== Create Dual-Y Plot ===%
figure;
yyaxis left
plot(t, v1, 'b-', 'LineWidth', 1.5);
ylabel('Channel 1 Voltage (V)');
grid on;

yyaxis right
plot(t, v2, 'r-', 'LineWidth', 1.5);
ylabel('Channel 2 Voltage (V)');

xlabel('Time (s)');
title('Rigol Dual-Channel Waveform');
legend('CH1','CH2');