%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ESpurbeck\Desktop\LANL Project\Marx Testing\Testing\12.11.25\Test_07_6_psi_91.7%_of_self_break_so_55kV_only_took_one_fire_command\Test_07_rigol1_20251211_101302.csv
%
% Auto-generated by MATLAB on 11-Dec-2025 12:54:45

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time_s", "ch1_v", "ch2_v"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Test_07_rigol1_20251211_101302 = readtable("C:\Users\ESpurbeck\Desktop\LANL Project\Marx Testing\Testing\12.11.25\Test_07_6_psi_91.7%_of_self_break_so_55kV_only_took_one_fire_command\Test_07_rigol1_20251211_101302.csv", opts);


%% Clear temporary variables
clear opts

time_s = Test_07_rigol1_20251211_101302.time_s;
ch1_v = Test_07_rigol1_20251211_101302.ch1_v;
ch2_v = Test_07_rigol1_20251211_101302.ch2_v;